### ISSUE TITLE
Versioning config & auto-update?

### ISSUE THREAD

**Issue by asmod3us** [jailmanager/jailman#117] opened 2020-05-24 20:26 UTC
Hello,

I'm using git to manage my own tweaks on jailman and keep my `config.yaml` versioned. I have a separate branch and rebase on master frequently. The autoupdate function does not play well with that, switching to master and discarding my committed modifications.

I wanted to see what others are using as a solution for keeping versioned modifications? I've disabled the call to `gitupdate` in `jailman.sh` in my branch for now.

**Comment by Ornias1993** [comment] 2020-05-24 21:21
@asmod3us 
Duplicate of #105 

This issue has been fixed for V1.3.0 (well isn't merged into dev yet, will be by then).
Simply put: v1.3.0 will update according to the git remote/branch you set on the folder, instead of a fixed setting.

**Closed by Ornias1993** 2020-05-24 21:21 UTC
Labels: duplicate, enhancement

**Comment by asmod3us** [comment] 2020-05-24 21:53
Hey, that's great! I'll have a look at 1.3...

**Comment by Ornias1993** [comment] 2020-05-26 11:56
@asmod3us On community request I reprioritised the auto-update fix.
It should now be included in 1.2.3 and can already be reviewed. See: #133
