### ISSUE TITLE
 Error when running dev version of jailman (Unexpected EOF)

### ISSUE THREAD

**Issue by uofirob** [jailmanager/jailman#172] opened 2020-06-02 18:57 UTC
###  Description
I've re-based my copy of jailman to the dev branch in order to test adding Lazy Librarian.  When running ./jailman.sh -r lazylibrarian (or any jail) I receive the following error: 
/root/jailman/includes/init_functions.sh: eval: line 138: unexpected EOF while looking for matching `"'

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  clone and switch to dev branch
2.  I changed my locations in the blueprints to mount my format of locations
3.  copy my config from my working version of jailman and change yml version to 1.3
4. run ./jailman.sh -r lazylibrarian (or any jail, or any command, -i, -d, -u have same issue)
5. receive error message.

**Comment by Ornias1993** [comment] 2020-06-02 19:08
@uofirob Are you sure you didn't mess up something?
There is no line 138 in initfunctions.sh...

**Comment by asmod3us** [comment] 2020-06-02 19:15
Cannot reproduce, just cloned a fresh copy of `dev`, ran reinstall on a blueprint - works for me. Can you share your config and produce a debug.log with `bash -xv jailman.sh -r lazylibrarian 2>&1 | tee debug.log` (review for sensitive information before submitting)?

**Comment by asmod3us** [comment] 2020-06-02 19:16
Plus the changes to the blueprint.

**Comment by uofirob** [comment] 2020-06-02 20:56
[debug.log](https://github.com/jailmanager/jailman/files/4719649/debug.log)
Changes to blueprint are: 
#!/usr/local/bin/bash
# This file contains the install script for lazylibrarian

#init jail
initblueprint "$1"

# Check if dataset for completed download and it parent dataset exist, create if they do not.
createmount "$1" "${global_dataset_downloads}"
**createmount "$1" "${global_dataset_downloads}"/LazyLibrarian /mnt/Complete**

# Check if dataset for media library and the dataset for books, comics and magazines exist, create if they do not.
createmount "$1" "${global_dataset_media}"
**createmount "$1" "${global_dataset_media}"/AudioBooks /media/AudioBooks
createmount "$1" "${global_dataset_media}"/Books /media/Books
createmount "$1" "${global_dataset_media}"/Comics /media/Comics
createmount "$1" "${global_dataset_media}"/Magazines /media/Magazines**

iocage exec "$1" "git clone https://gitlab.com/LazyLibrarian/LazyLibrarian.git /usr/local/share/lazylibrarian"
**iocage exec "$1" "git clone git://github.com/urllib3/urllib3.git /urllib3"** 
iocage exec "$1" "python /urllib3/setup.py install"
iocage exec "$1" "rm -r /urllib3"
iocage exec "$1" "pw user add lazylibrarian -c lazylibrarian -u 111 -d /nonexistent -s /usr/bin/nologin"
iocage exec "$1" chown -R lazylibrarian:lazylibrarian /usr/local/share/lazylibrarian /config
iocage exec "$1" mkdir /usr/local/etc/rc.d
cp "${includes_dir}/lazylibrarian.rc /mnt/"${global_dataset_iocage}"/jails/"$1"/root/usr/local/etc/rc.d/lazylibrarian
iocage exec "$1" chmod u+x /usr/local/etc/rc.d/lazylibrarian
iocage exec "$1" sysrc "lazylibrarian_enable=YES"
iocage exec "$1" sed -i '' -e 's|/var/run/lazylibrarian/lazylibrarian.pid|/config/lazylibrarian.pid|g' /usr/local/etc/rc.d/lazylibrarian
iocage exec "$1" "pkg update && pkg upgrade -y"
iocage exec "$1" service lazylibrarian start

exitblueprint "$1" "Lazy Librarian is now available at http://${jail_ip}:5299"

**Comment by Ornias1993** [comment] 2020-06-02 20:58
@uofirob next time please use code tags.

**Comment by Ornias1993** [comment] 2020-06-02 20:59
@uofirob care to also post a copy of (remove personal details please) of your config.yml?

**Comment by asmod3us** [comment] 2020-06-02 21:00
You have a syntax error in your blueprint

**Comment by asmod3us** [comment] 2020-06-02 21:00
line 25:
```cp "${includes_dir}/lazylibrarian.rc /mnt/"${global_dataset_iocage}"/jails/"$1"/root/usr/local/etc/rc.d/lazylibrarian
```

**Comment by asmod3us** [comment] 2020-06-02 21:01
there's five double quote chars in there...

**Comment by asmod3us** [comment] 2020-06-02 21:01
my guess is it's supposed to read like this:
```
cp "${includes_dir}/lazylibrarian.rc" "/mnt/${global_dataset_iocage}/jails/$1/root/usr/local/etc/rc.d/lazylibrarian"
```

**Comment by asmod3us** [comment] 2020-06-02 21:02
and you can use `${jail_root}` for the long path:
```
cp "${includes_dir}/lazylibrarian.rc" "${jail_root}/usr/local/etc/rc.d/lazylibrarian"
```

**Comment by uofirob** [comment] 2020-06-02 22:00
That still hasn't fixed it.  Here's a copy of my Config.yml
[config.yml.txt](https://github.com/jailmanager/jailman/files/4719904/config.yml.txt)

**Comment by Ornias1993** [comment] 2020-06-02 22:02
@uofirob A fix for some of the errors has just been merged.
Please rebase...

**Comment by asmod3us** [comment] 2020-06-02 22:16
What errors are you seeing after fixing the blueprint shell script?
Your yaml file has a few issues as well:

```
❯ yamllint foo.yaml
foo.yaml
  7:4       warning  wrong indentation: expected 4 but found 3  (indentation)
  10:30     error    trailing spaces  (trailing-spaces)
  15:4      warning  wrong indentation: expected 4 but found 3  (indentation)
  21:8      error    trailing spaces  (trailing-spaces)
  26:1      error    trailing spaces  (trailing-spaces)
  27:10     error    trailing spaces  (trailing-spaces)
  31:1      error    trailing spaces  (trailing-spaces)
  32:10     error    trailing spaces  (trailing-spaces)
  36:1      error    trailing spaces  (trailing-spaces)
  37:10     error    trailing spaces  (trailing-spaces)
  42:9      error    trailing spaces  (trailing-spaces)
  52:7      error    trailing spaces  (trailing-spaces)
  56:1      error    trailing spaces  (trailing-spaces)
  57:11     error    trailing spaces  (trailing-spaces)
  61:1      error    trailing spaces  (trailing-spaces)
  62:12     error    trailing spaces  (trailing-spaces)
  66:1      error    trailing spaces  (trailing-spaces)
  67:12     error    trailing spaces  (trailing-spaces)
  71:1      error    trailing spaces  (trailing-spaces)
  72:16     error    trailing spaces  (trailing-spaces)
  76:1      error    trailing spaces  (trailing-spaces)
  77:13     error    trailing spaces  (trailing-spaces)
  85:1      error    syntax error: found character '\t' that cannot start any token (syntax)
  86:1      error    trailing spaces  (trailing-spaces)
  87:11     error    trailing spaces  (trailing-spaces)
  93:1      error    trailing spaces  (trailing-spaces)
  102:12    error    trailing spaces  (trailing-spaces)
  115:1     warning  too many blank lines (1 > 0)  (empty-lines)
```

Most notably, the indentation for the dataset is off (3 instead of 4). Our yaml parser is a giant hack, try fixing that and see how it goes. Here's a cleaned up version:
```
global:
  # Config file syntax version (not same as script version)
  version: 1.3
  # Relevant dataset paths, please use the ZFS dataset syntax such as: tank/apps
  dataset:
   # dataset for internal jail config files
    config: tank/Apps
    # Media library dataset
    media: Volume1/media
    # Parent downloads dataset
    # (is going to contain: Complete and Incomplete datasets for downloads)
    downloads: Volume1/media/Downloads
  jails:
   # jail version to install
    version: 11.3-RELEASE
    # Global pkgs to install in all jails.
    # Please use standard space delimited pkg install syntax.
    pkgs: curl ca_root_nss bash

jail:
  plex:
    blueprint: plex
    ip4_addr: 192.168.2.128/24
    gateway: 192.168.2.1
    beta: true

  lidarr:
    blueprint: lidarr
    ip4_addr: 192.168.2.124/24
    gateway: 192.168.2.1

  sonarr:
    blueprint: sonarr
    ip4_addr: 192.168.2.122/24
    gateway: 192.168.2.1

  radarr:
    blueprint: radarr
    ip4_addr: 192.168.2.123/24
    gateway: 192.168.2.1

  mylar:
    blueprint: mylar
    ip4_addr: 192.168.2.126/24
    gateway: 192.168.2.1

  lazylibrarian:
    blueprint: lazylibrarian
    ipr_addr: 192.168.2.125/24
    gateway: 192.168.2.1

  kms:
    blueprint: kms
    ip4_addr: 192.168.2.127/24
    gateway: 192.168.2.1

  jackett:
    blueprint: jackett
    ip4_addr: 192.168.2.121/24
    gateway: 192.168.2.1

  organizr:
    blueprint: organizr
    ip4_addr: 192.168.2.120/24
    gateway: 192.168.2.1

  tautulli:
    blueprint: tautulli
    ip4_addr: 192.168.2.130/24
    gateway: 192.168.2.1

  transmission:
    blueprint: transmission
    ip4_addr: 192.168.2.99/24
    gateway: 192.168.2.1

  nextcloud:
    blueprint: nextcloud
    ip4_addr: 192.168.2.99/24
    gateway: 192.168.2.1
    time_zone: America/Chicago
    host_name: cloud.example.com
    db_jail: "mariadb"
    admin_password: "ADMINPASSWORDHERE"
    db_password: "DBPASSWORDHERE"

  mariadb:
    blueprint: mariadb
    ip4_addr: 192.168.2.98/24
    gateway: 192.168.2.1
    db_root_password: ADMINPASSWORDHERE
    host_name: mariadb.local.example

  bitwarden:
    blueprint: bitwarden
    ip4_addr: 192.168.2.97/24
    gateway: 192.168.2.1
    db_jail: "mariadb"
    db_password: "DBPASSWORDHERE"
    admin_token: "PUTYOURADMINTOKENHEREANDREMOVETHIS"

  influxdb:
    blueprint: influxdb
    ip4_addr: 192.168.2.250/24
    gateway: 192.168.2.1

  unifi:
    blueprint: unifi
    ip4_addr: 192.168.2.251/24
    gateway: 192.168.2.1
    unifi_poller: true
    db_jail: influxdb
    up_db_password: unifi-poller
    up_password: upoller
```

**Comment by uofirob** [comment] 2020-06-03 04:03
ok, so I've gone back and done this.  I've reset my branch to get latest.  I copied the sample config over my existing one and the only change I made was to change the mount locations to tank/Apps, media: Volume1/media and downloads: Volume1/media/Downloads.

I went down to my lazylibrarian entry at the bottom, renamed it to lazylibrarianjail (naming conventions) changed ip to 192.168.2.125/24 and gateway to 192.168.2.1 and saved.

In jailman.sh I commented out the update line (to make sure my changes kept)

In /blueprints/lazylibrarian/install.sh I made the changes to mount locations like in the file above but I manually did them and then I also changed the cp line to the one mentioned above.  Now I'm getting this error: 
`
root@freenas[~/uofirobjailman]# ./jailman.sh -i lazylibrarianjail
Working directory for jailman.sh is: /root/uofirobjailman
jails to install lazylibrarianjail
Installing lazylibrarianjail
Checking config...
/root/uofirobjailman/includes/global_functions.sh: line 24: !jaildhcp: unbound variable
`

which corresponds to this line in the globalfunctions: `blueprintextraconf="blueprint_${blueprint}_custom_iocage"`

Is that ${blueprint} an unbound variable?

**Comment by asmod3us** [comment] 2020-06-03 08:31
That is indeed something we can fix!

**Comment by asmod3us** [comment] 2020-06-03 08:37
I've opened a PR to fix this. Let us know how it goes! It's a change on just one line if you don't want to wait for the merge.

Noticed one more error in the posted config.yml: `ip4_addr` instead of `ipr_addr`.
```
  lazylibrarian:
    blueprint: lazylibrarian
    ipr_addr: 192.168.2.125/24
    gateway: 192.168.2.1
```

**Comment by Ornias1993** [comment] 2020-06-03 09:40
@asmod3us merged and fixed already...

**Closed by Ornias1993** 2020-06-03 09:40 UTC
Labels: bug

**Comment by uofirob** [comment] 2020-06-03 13:22
So I got latest and rebased and now all of my lazylibrarian stuff is gone and it looks like it's gone back to 1.2 (config.yml.example, no lazylibrarian)

**Comment by uofirob** [comment] 2020-06-03 13:37
I've tried to run it again and still I get 
`root@freenas[~/uofirobjailman]# ./jailman.sh -i lazylibrarianjail
Working directory for jailman.sh is: /root/uofirobjailman
jails to install lazylibrarianjail
Installing lazylibrarianjail
Checking config...
/root/uofirobjailman/includes/global_functions.sh: line 24: !jaildhcp: unbound variable
`
I've done the following: 
`git reset --hard
git checkout master
git branch -D NewInstalls
git checkout NewInstalls
`
I then go and make my changes I've stated above (mount locations in lazylibrarian blueprint, fix the cp line, explicitly add directory for urllib3 to target, turn off auto-update.
When I run the install command I still get that error about the unbound variable.
I've verified my config has ip4_addr

What am I doing wrong?

**Comment by asmod3us** [comment] 2020-06-03 14:31
i'm guessing based on the above you ran off of master but the fix is only in dev

**Comment by uofirob** [comment] 2020-06-03 18:49
My NewInstalls branch is based off of jailman/dev branch

**Comment by asmod3us** [comment] 2020-06-03 19:05
I ran your config with the dev branch and I don't see this error anymore.

Did you fetch the latest changes from dev?
Check the status of the file where we fixed this issue. It should look like this:

```
❯ git log -n1 includes/global_functions.sh
commit 54db0a2135382b07661173deb836ba328169cee4
Author: asmod3us <4sm0d3us@gmail.com>
Date:   Wed Jun 3 10:33:59 2020 +0200

    Fixes #172. no undef for setdhcp
```

What is on your branch? `git diff --name-only dev..NewInstalls` should only show changes to your files.

**Comment by uofirob** [comment] 2020-06-03 19:41
I think it was because I blew the directory away yesterday I lost my upstream link.  I have it executing now, but I'm getting an unbound variable error: 
`
environment: line 13: !linkblueprint: unbound variable
ERR - status code 1
Command:  "${SCRIPT_DIR}"/blueprints/"${!blueprint}"/install.sh "${jail}"
Location:  ./jailman.sh, line 171
Status: 0
Stack trace:
    [1] main(): ./jailman.sh, line 171 -> main
`
which corresponds to this line:
`jailcreate "${jail}" "${!blueprint}" && "${SCRIPT_DIR}"/blueprints/"${!blueprint}"/install.sh "${jail}"`

**Comment by asmod3us** [comment] 2020-06-03 19:51
Strange - are you using traefik with your blueprint? Please share more context, i.e.:

1. current `config.yml`
2. debug log as above: `bash -xv jailman.sh -r lazylibrarian 2>&1 | tee debug.log`
3. we're still unclear about the state of your modifications to the branch? What is the output of the requested git diff?

**Comment by asmod3us** [comment] 2020-06-03 20:32
@Ornias1993 only line i can find that references `!linkblueprint` is in `includes/blueprint_functions, initblueprint` line 25. Can you take a look?

```
			linkvarlist=blueprint_${!linkblueprint}_vars
```
seems to crap out and

```
			linkblueprint=jail_${val}_blueprint
```
as not contain a known variable name?

**Comment by Ornias1993** [comment] 2020-06-03 20:40
@asmod3us Okey, i'm going to intervene now.

I already ask to keep discussions about the Lazy Libarian, limited to the PR. This is one big blob of "offtopic."

**Comment by asmod3us** [comment] 2020-06-03 20:42
Mhh, I think there is something going on with linkblueprint. I'll open a new issues.

**Comment by Ornias1993** [comment] 2020-06-03 20:45
It basically means ${val} is empty I guess.

**Comment by asmod3us** [comment] 2020-06-03 20:49
Investigating in #175.
